require: rubocop-rails
AllCops:
  NewCops: enable
Style/Documentation:
  Enabled: false
Rails/FilePath:
  Enabled: false
Rails/UniqueValidationWithoutIndex:
  Enabled: false
Lint/NonLocalExitFromIterator:
  Enabled: false
Style/RedundantBegin:
  Enabled: false
Style/MultilineTernaryOperator:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Naming/MethodName:
  Enabled: false
Rails/BulkChangeTable:
  Enabled: false
